# make sure you change application name to whatever you Google Application name is
application: berastau
version: 1
runtime: python
api_version: 1

handlers:
- url: /public
  static_dir: public
- url: .*
  script: main.py


